targets:
  $default:
    builders:
      cqrs_mediatr_flutter:mediatr_builder:
        enabled: true
        options: 
          generate_path: 'data/tool'

builders:
  mediatr_builder:
    import: "package:cqrs_mediatr_flutter/src/mediatr_builder.dart"
    builder_factories: ["mediatrBuilder"]
    build_extensions: {"$lib$": [".dart_tool/flutter_gen/cqrs/mediatr.dart"]}
    auto_apply: dependents
    build_to: cache