name: cqrs_mediatr_flutter
description: "It is a CQRS Dart package with a code generation structure suitable for the result pattern relationship in backend APIs, where you can easily apply the CQRS design pattern in Dart projects."
version: 1.0.5
maintainer: Ahmet Güler (@AhmetGuler1995)
homepage: https://github.com/AhmetGuler1995/cqrs_mediatr_flutter
repository: https://github.com/AhmetGuler1995/cqrs_mediatr_flutter.git

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  glob: ^2.1.3
  source_gen: ^2.0.0
  analyzer: ^7.4.5
  build: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15


build:
source_gen:


flutter: